"""empty message

Revision ID: 1840f657eaf6
Revises: 191550afd2d7
Create Date: 2025-03-03 01:40:52.241201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1840f657eaf6'
down_revision = '191550afd2d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evento_dj',
    sa.Column('id_evento', sa.Integer(), nullable=False),
    sa.Column('id_dj', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_dj'], ['djs.id'], ),
    sa.ForeignKeyConstraint(['id_evento'], ['eventos.id_evento'], ),
    sa.PrimaryKeyConstraint('id_evento', 'id_dj')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evento_dj')
    # ### end Alembic commands ###
