"""empty message

Revision ID: 191550afd2d7
Revises: 5642b2a7fc21
Create Date: 2025-03-03 01:10:41.034129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '191550afd2d7'
down_revision = '5642b2a7fc21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###
