"""empty message

Revision ID: 2985be65fa06
Revises: 477a7df81af7
Create Date: 2025-03-05 00:45:58.640812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2985be65fa06'
down_revision = '477a7df81af7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs_inventario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs_inventario', schema=None) as batch_op:
        batch_op.drop_column('usuario')

    # ### end Alembic commands ###
