"""empty message

Revision ID: 44089588bd6a
Revises: 2985be65fa06
Create Date: 2025-03-05 01:06:21.720147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44089588bd6a'
down_revision = '2985be65fa06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objetos_inventario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objetos_inventario', schema=None) as batch_op:
        batch_op.drop_column('activo')

    # ### end Alembic commands ###
