"""empty message

Revision ID: 477a7df81af7
Revises: e1208cb684d0
Create Date: 2025-03-05 00:13:49.845642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '477a7df81af7'
down_revision = 'e1208cb684d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs_inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('objeto_id', sa.Integer(), nullable=False),
    sa.Column('objeto_nombre', sa.String(length=100), nullable=False),
    sa.Column('cantidad_anterior', sa.Integer(), nullable=True),
    sa.Column('cantidad_nueva', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['objeto_id'], ['objetos_inventario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logs_inventario')
    # ### end Alembic commands ###
