"""empty message

Revision ID: 7448a45a988f
Revises: 44089588bd6a
Create Date: 2025-03-19 16:19:29.748510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7448a45a988f'
down_revision = '44089588bd6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kuyen_coins', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('kuyen_coins')

    # ### end Alembic commands ###
