"""empty message

Revision ID: 972663eac0e3
Revises: 7448a45a988f
Create Date: 2025-03-19 16:44:07.298004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '972663eac0e3'
down_revision = '7448a45a988f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recompensas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recompensas_canjeadas',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('recompensa_id', sa.Integer(), nullable=False),
    sa.Column('fecha_canje', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recompensa_id'], ['recompensas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'recompensa_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recompensas_canjeadas')
    op.drop_table('recompensas')
    # ### end Alembic commands ###
